apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: prow-jobs-scraper-vbeb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: prow-jobs-scraper-vbeb
    app.kubernetes.io/part-of: prow-jobs-scraper
  name: prow-jobs-scraper-vbeb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: prow-jobs-scraper-vbeb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: prow-jobs-scraper-vbeb
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/prow-jobs-scraper/prow-jobs-scraper-vbeb@sha256:06ff3b2f0f386e7bfa4b27f603a35287b42cc08a91cc430dd985aa126c96ce3f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9200
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
