apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: prow-jobs-scraper-vbeb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: prow-jobs-scraper-vbeb
    app.kubernetes.io/part-of: prow-jobs-scraper
  name: prow-jobs-scraper-vbeb5gim
spec:
  port:
    targetPort: 9200
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: prow-jobs-scraper-vbeb
    weight: 100
status: {}
